Allow requesting IRCv3 extended-join capability
Throne3d/node-irc pull request #67
Opened 2018-10-08 01:50 UTC by Fusl

Standard IRC `JOIN` messages look like this:
```
:nick!ident@host JOIN #channelname
```

IRCv4 `JOIN` messages look like this:
```
:nick!ident@host JOIN #channelname * :Fusl
```
or
```
:nick!ident@host JOIN #channelname authenticated-username :Fusl
```

`message.args[1]` will be the authenticated username and `message.args[2]` the real name.

2018-10-08 22:21 UTC, Throne3d commented on lib/irc.js
>                  // currently only handle ACK sasl responses
Nitpick: this no longer only handles ACKs for sasl, so could you amend this? ("currently only handles ACK sasl and extended-join", for example)

2018-10-08 22:21 UTC, Throne3d commented on lib/irc.js
> +    if (this.opt.extendedJoin) {
Can you add a link to https://ircv3.net/specs/extensions/extended-join-3.1.html here?

2018-10-08 22:21 UTC, Throne3d commented on lib/irc.js
> +        extendedJoin: false
If you could add a note to the API documentation about `extendedJoin`, that would be great.

2018-10-08 22:23 UTC, Throne3d commented
I'm a little confused about the motivation behind this PR - without [account-notify](https://ircv3.net/specs/extensions/account-notify-3.1.html), won't [extended-join](https://ircv3.net/specs/extensions/extended-join-3.1.html) do very little to modify the experience as a user of the library? I'm okay accepting it anyway, it just seems like it won't be very useful.

I'd like this code to interact well with a `CAP NAK` response, so that if we request `extended-join`, and get told that it's not supported, we still successfully respond with `CAP END`. I'm happy if this is emitted as an error at the same time.

Could you also add some tests for this? Primarily, ensure that:
- it requests the capability when enabled and SASL is disabled, and responds with `CAP END` if it receives a response
- it does not request the capability when disabled
- with SASL enabled, it requests both `sasl` and `extended-join`, then waits for a SASL-related CAP response before sending `CAP END`

(I'm okay with, for now, assuming the responses come in a timely and ordered fashion, and accordingly that we won't enter a state where we have a response for `sasl` but not for `extended-join` for a prolonged amount of time - this could cause weirdness where we respond with `CAP END` and `extended-join` fails to get registered, but it seems unlikely to happen. Ideally, if any future capability negotiation is added to this library, the system will be refactored.)

Thanks for your contribution!

2018-10-08 22:24 UTC, Throne3d requested changes
(Per comment)

2018-10-09 00:42 UTC, Fusl commented
> I'm a little confused about the motivation behind this PR - without account-notify, won't extended-join do very little to modify the experience as a user of the library?

I have a bot that automatically voices users and voices them immediately when they are authenticated: https://github.com/opennic/irc-bot-openvoice/blob/master/openvoice.js#L121

2019-01-01 11:17 UTC, tritium21 commented
@Throne3d The information that is already on the bot config or the welcome message is the *bot*'s authenticated name, etc.  The extended join message also adds authenticated names for all *other users* who join a channel.

2019-04-08 14:24 UTC, Throne3d commented
Any chance you'll get to the requested changes soon?

2024-07-29 03:52 UTC, closed without merging